spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jybiquge?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: zjhyyds
    driver-class-name: com.mysql.cj.jdbc.Driver
    #druid数据连接池配置
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 20 #初始化数据库连接池大小
      min-idle: 10 #空闲数
      max-active: 100 #最大连接数
